-- Transport services histogram

prompt HISTOGRAM
SELECT FREQUENCY, DURATION FROM
V$REDO_DEST_RESP_HISTOGRAM 
WHERE DEST_ID=2 AND FREQUENCY>1;

prompt MAX DURATION
SELECT max(DURATION) 
FROM V$REDO_DEST_RESP_HISTOGRAM 
WHERE DEST_ID=2 AND FREQUENCY>1;


prompt MIN DURATION
SELECT MIN(DURATION) 
FROM V$REDO_DEST_RESP_HISTOGRAM 
WHERE DEST_ID=2 AND FREQUENCY>1;

