SELECT * FROM table (
   DBMS_XPLAN.DISPLAY_CURSOR('&sql', NULL, 'ALLSTATS ALL'))
/


SELECT * FROM table (
   DBMS_XPLAN.DISPLAY_CURSOR('&sql', NULL, 'ADVANCED ALLSTATS ALL -PROJECTION +ADAPTIVE'))
/


SELECT * FROM table (
   DBMS_XPLAN.DISPLAY_CURSOR('&sql', NULL, 'ADVANCED ALLSTATS ALL -PROJECTION +ADAPTIVE +HINT_REPORT'))
/
