
CREATE OR REPLACE TYPE SYS.XPS_STRING_AGG AUTHID CURRENT_USER AS OBJECT
(
  CURR_STR    VARCHAR2(32767),
  CURR_STR_C  CLOB,

  STATIC FUNCTION ODCIAGGREGATEINITIALIZE(SCTX IN OUT XPS_STRING_AGG) RETURN NUMBER,

  MEMBER FUNCTION ODCIAGGREGATEITERATE(SELF IN OUT XPS_STRING_AGG, P1 VARCHAR2) RETURN NUMBER,

  MEMBER FUNCTION ODCIAGGREGATETERMINATE(SELF XPS_STRING_AGG, RETURNVALUE OUT CLOB, FLAGS NUMBER) RETURN NUMBER,

  MEMBER FUNCTION ODCIAGGREGATEMERGE(SELF IN OUT XPS_STRING_AGG, SCTX2 XPS_STRING_AGG) RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY SYS.XPS_STRING_AGG IS
  STATIC FUNCTION ODCIAGGREGATEINITIALIZE(SCTX IN OUT XPS_STRING_AGG) RETURN NUMBER IS
  BEGIN
    SCTX := XPS_STRING_AGG(NULL,NULL) ;
    RETURN ODCICONST.SUCCESS;
  END;

  MEMBER FUNCTION ODCIAGGREGATEITERATE(SELF IN OUT XPS_STRING_AGG, P1 VARCHAR2) RETURN NUMBER IS
  BEGIN
    IF (CURR_STR_C IS NULL AND (CURR_STR IS NULL OR LENGTH(CURR_STR)<29950)) THEN
      IF(CURR_STR IS NOT NULL) THEN
        CURR_STR := CURR_STR || ',' || P1;
      ELSE
        CURR_STR := P1;
      END IF;
    ELSE
      IF (CURR_STR_C IS NULL) THEN
        CURR_STR_C := CURR_STR ;
        CURR_STR := NULL ;
      END IF ;

      CURR_STR_C := CURR_STR_C || ',' || P1;
    END IF ;

    RETURN ODCICONST.SUCCESS;
  END;

  MEMBER FUNCTION ODCIAGGREGATETERMINATE(SELF XPS_STRING_AGG, RETURNVALUE OUT CLOB, FLAGS NUMBER) RETURN NUMBER IS
  BEGIN
    IF (CURR_STR IS NOT NULL) THEN
      RETURNVALUE := CURR_STR ;
    ELSE
      RETURNVALUE := CURR_STR_C ;
    END IF ;

    RETURN ODCICONST.SUCCESS;
  END;

  MEMBER FUNCTION ODCIAGGREGATEMERGE(SELF IN OUT XPS_STRING_AGG, SCTX2 XPS_STRING_AGG) RETURN NUMBER IS
  BEGIN
    IF(SCTX2.CURR_STR IS NOT NULL) THEN
      SELF.CURR_STR := SELF.CURR_STR || ',' || SCTX2.CURR_STR ;
    END IF;

    RETURN ODCICONST.SUCCESS;
  END;
  end;
/

CREATE OR REPLACE FUNCTION SYS.XPS_AGGREGATE(P1 VARCHAR2) RETURN CLOB AGGREGATE USING XPS_STRING_AGG ;
/

create public synonym wm_concat for SYS.XPS_AGGREGATE;

grant execute on SYS.XPS_AGGREGATE to public;

